apiVersion: apps/v1
kind: Deployment
metadata:
  name: vran-node-deployment
  labels:
    app: vran-node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vran-node
  template:
    metadata:
      labels:
        app: vran-node
    spec:
      containers:
      - name: vran-node
        image: vran-node:v1.0
        imagePullPolicy: Never
        resources:
          limits:
            cpu: "200m"
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "64Mi"
